### ISSUE TITLE
Privileged needed?

### ISSUE THREAD

**Issue by GioF71** [mbentley/docker-apt-cacher-ng#3]
Hello Matt, 
I am running you image with this compose file:

```text
---
version: '3'

services:
  apt-cacher-ng:
    image: mbentley/apt-cacher-ng:latest
    container_name: apt-cacher-ng
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
    ports:
      - 3142:3142
    volumes:
      - ./acng.conf:/etc/apt-cacher-ng/acng.conf:ro
      - /mnt/local/qvo1tb/docker-data/apt-cache-ng/mbentley:/var/cache/apt-cacher-ng
```

I was browsing its web interface and I noticed that the "usage" links does not work. I tried an older version from 20220301 but the behavior is the same.
So I went to the container logs and noticed this:

```text
apt-cacher-ng    | Setting permissions on /var/cache/apt-cacher-ng, /var/log/apt-cacher-ng, and /var/run/apt-cacher-ng...done
apt-cacher-ng    | 
apt-cacher-ng    | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
apt-cacher-ng    | rsyslogd: activation of module imklog failed [v8.2102.0 try https://www.rsyslog.com/e/2145 ]
```

After some research, I found out that this issue can be solved by adding the privileged flag. so the stack would become:

```text
---
version: '3'

services:
  apt-cacher-ng:
    image: mbentley/apt-cacher-ng:latest
    container_name: apt-cacher-ng
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
    ports:
      - 3142:3142
    volumes:
      - ./acng.conf:/etc/apt-cacher-ng/acng.conf:ro
      - /mnt/local/qvo1tb/docker-data/apt-cache-ng/mbentley:/var/cache/apt-cacher-ng
```

The issue on the container log output disappeared after that. The usage link is still not working though.
Did you notice the same behavior?
I am running Debian Buster AMD64.

```text
power@gruesome03:~/git/stack/gruesome03/apt-cacher-ng$ uname -a
Linux gruesome03 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
power@gruesome03:~/git/stack/gruesome03/apt-cacher-ng$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

Thank you for any feedback
Giovanni

**Comment by mbentley** [comment]
I don't think that it really makes any difference in terms of functionality either way, the logs are still being written to `/var/log/apt-cacher-ng`.

I can also have it skip this: https://stackoverflow.com/a/60265997 as I am pretty sure that rsyslog is only being used to write logs (it's been a while since I created this image) so I actually don't recall specifically why rsyslog is included; might be for cron logging which is in place to rotate log files.

**Comment by mbentley** [comment]
Submitted #4 to disable the attempt to load the unnecessary kernel module.

**Comment by mbentley** [comment]
Updated image should now be on Docker Hub that no longer throws an error.  Privileged mode isn't required and shouldn't be set for the image to function.

**Comment by GioF71** [comment]
Hello, I can confirm that the issue is gone.
Thank you!
