### ISSUE TITLE
acng-report.html not available when using volume for acng.conf

### ISSUE THREAD

**Issue by GioF71** [mbentley/docker-apt-cacher-ng#5]
Hello again Matt, 

with the following compose file:

```text
---
version: '3'

services:
  apt-cacher-ng:
    image: mbentley/apt-cacher-ng:latest
    container_name: apt-cacher-ng
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
    ports:
      - 3142:3142
    volumes:
      - ./acng.conf:/etc/apt-cacher-ng/acng.conf:ro
      - /mnt/local/qvo1tb/docker-data/apt-cache-ng/mbentley:/var/cache/apt-cacher-ng
```
The statistic page available at {host}:{post}/acng-report.html does not show and the main page itself has a name that starts with "Not found".
If I comment out the acng.conf volume, everything comes back to normal.
Of course this is a minor issue, the functionality is not affected.

While writing the issue I realize that the acng.conf file that I provide should be complete, and not only include the exclusions as I am doing.
Could you consider making the volume file a place for specifying the exclusions only, so maybe you could append that content to the original configuration file?
Otherwise, one should have a full apt-cacher-ng config file, which has recently changed (see your "reuse connections" change. Those changes might be lost if one uses the volume.

Thank you for any feedback

**Comment by mbentley** [comment]
I am honestly not sure - is there a sort of "include file" behavior for apt-cacher-ng to allow that?  If so, I am happy to add support for it in whatever way it can be.

**Comment by GioF71** [comment]
Hello, I can confirm the "issue". I copied the contents of the original acng.conf from the container running with acng.conf _not mounted_ and combined that with my exclusions (with are only basically https repositories).
Now I can use the resulting file properly, the exclusions work, and the web interface also works properly.

So my conclusion: when using the acng.conf volume, we should provide a valid configuration file, not only the exclusions.

I don't know about any include feature in apt-cacher-ng, I will look into it tomorrow in the morning (I am in Italy) and let you know.

Thank you for your attention!

**Comment by mbentley** [comment]
Just from looking through the config file really quickly, it doesn't appear that there is an out of the box config structure like how some other apps have the ability to combine multiple config files (many cases something like an `/etc/<app>.d/` directory where multiple config files can be dropped in and parsed essentially as one.  I would expect that if it was possible, it would at least include some sort of reference to that capability in the config but I saw nothing from a quick grep.

**Comment by GioF71** [comment]
Yes, I came to the same conclusion after a quick research.
I do not see a clean way to differentiate some "append_mode" and still support a complete override of the configuration file.
Maybe you could support the exclusions via environment variables, with an array of variable names (EXCLUDE_01 .. EXCLUDE_10) and add those lines to acng.conf when starting apt-cacher-ng.

Or, considering append_mode again, maybe with a simple variable named ACNG_CONF_APPEND_MODE, with default set to "NO" or something similar, we could regulate how the mounted acng.conf is treated: as a full replacement of the default acng.conf or as a portion to be appended to it.

I don't believe any of the solutions are optimal, but unfortunately apt-cacher-ng does not seem to support anything more elegant.
Does at least one of the solution sound feasible to you? If so, I might help with the changes and do a PR if you want, let me know.

Thank you

**Comment by GioF71** [comment]
Hello Matt, considering that apt-cacher-ng cannot really cache repositories using https (ref [here](https://wiki.debian.org/AptCacherNg) at "HTTPS repositories"), maybe a simple solution might be adding this line to your Dockerfile:

```code
echo "PassThroughPattern: ^(.*):443$" >> /etc/apt-cacher-ng/acng.conf &&\
```
just under the line:

```code
echo "PassThroughPattern: .*" >> /etc/apt-cacher-ng/acng.conf &&\
```
Basically the only exclusion I need is this one, and I could avoid to have a full acng.conf file to be mounted (and of course to be kept maintained).
I think this is probably what most people need, you can see around there are many suggestions for exclusions for download.docker.com, armbian.com, but ultimately all of those exclusions are not needed if https is excluded.

Maybe appending this line or not can be governed through an environment variable. 
Please let me know if you think this is feasible.

Thank you!
Giovanni

**Comment by mbentley** [comment]
Hmm, yeah, so I don't recall exactly why I changed the `PassThroughPattern` in https://github.com/mbentley/docker-apt-cacher-ng/commit/6ca2c499bed79540965093b7f5c1c231eaa537b7 but the goal was to just allow all HTTPS requests to automatically be passed through.  Checking the Debian Wiki for apt-cacher-ng, it is indeed suggesting `PassThroughPattern: ^(.*):443$`.  I will build an image with this pattern and use it for a bit to see if there are any unexpected effects in my environment before merging a PR.

I use apt-cacher-ng extensively in my Docker image build system so I should be able to find out pretty quickly if something isn't working correctly.

**Comment by mbentley** [comment]
Image is on Docker Hub: `mbentley/apt-cacher-ng:test`; PR is at https://github.com/mbentley/docker-apt-cacher-ng/pull/6

**Comment by GioF71** [comment]
Hello, sorry for answering late, but I am on holiday for a few days. I am about to try your new images.
Thanks for your work!

**Comment by GioF71** [comment]
Hello, I tested the latest version on the arm architecture, everything seems to be working properly.
Exclusions are not needed anymore client-side. This is awesome, thank you!

**Comment by mbentley** [comment]
Good deal - glad to hear that the updated pattern is working well!
