### ISSUE TITLE
Why the switch back to bullseye?

### ISSUE THREAD

**Issue by adhawkins** [mbentley/docker-apt-cacher-ng#7]
Hi,

Looking at replacing my home grown container with yours, and was just browsing through the source.

Interested as to why you made the decision to go back to bullseye from bookworm?

Thanks

**Comment by mbentley** [comment]
I had issues with the version in bookworm originally.  It was failing to function properly, throwing errors, when multiple clients were access it in parallel.  If I recall correctly, this is what I was seeing: https://bugs.launchpad.net/ubuntu/+source/apt-cacher-ng/+bug/1983856 (even though it is the Ubuntu bug repo).

**Comment by adhawkins** [comment]
Ah ok, thanks for clarifying. I don't have that many clients, so am unlikely to run in to this. Sticking with your version seems to make sense though.

Thanks again for taking the time to explain.

**Comment by mbentley** [comment]
Well, I've seen random issues where the apt just completely hangs during an update with trixie so I've added tags for trixie, bookworm, and bullseye.  I will probably be moving back to bullseye myself and potentially looking for alternate solutions because if there are bugs like this that make it through the entire life of bookworm and are still present in trixie, I just don't see them getting fixed.

**Comment by adhawkins** [comment]
Has it been reported to Debian do you know?

**Comment by mbentley** [comment]
That’s where I can’t tell 100% based on the errors or lack of of it is the same issue as what is described in the launchpad bug or not but I believe it is.

**Comment by adhawkins** [comment]
Thanks for the update.

I have multiple Debian VMs in my network for work, which is the prime reason I use a cache. However, now that I have gigabit internet then I guess there's an argument for it being a little un-necessary (other than reducing the load on Debian's servers I guess).

**Comment by mbentley** [comment]
I will say that despite having gigabit internet myself as well, I find that having a cache is still really helpful considering that so many mirrors are kinda slow but if you don't have that many machines or if you're not interested in speed, I can see where that might not be as compelling.
